### ISSUE TITLE
Dependency on wieni/wmcontroller

### ISSUE THREAD

**Issue by RobinHoutevelts** [wieni/wmsingles#3]
In https://github.com/wieni/wmsingles/commit/40e70a77ef91beb109dd3b8009196d57efc5841c a dependency to [wieni/wmcontroller](https://github.com/wieni/wmcontroller) sneaked in 👀 

It's safe to just swap to core's `ControllerBase` instead.

**Comment by spoit** [comment]
That's an accident. Fixing
